dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"
  - file="docker-compose.yml"

script:
  - cd "$dir"
  # Test containers build
  - travis_retry docker-compose -f ${file} build
  # Test containers run
  - docker-compose -f ${file} up -d && sleep 60
  - docker-compose -f ${file} ps
  - docker-compose -f ${file} logs
  - docker-compose -f ${file} ps "taiga_front" | grep "Up"
  # Test containers can be dropped and restarted
  - docker-compose -f ${file} down
  - docker-compose -f ${file} up -d && sleep 60
  - docker-compose -f ${file} ps
  - docker-compose -f ${file} logs
  - docker-compose -f ${file} ps "taiga_front" | grep "Up"

after_script:
  - docker images
  - docker ps -a

notifications:
  email: false

env: # Environments
    - VERSION=3.3 VARIANT=alpine
    - VERSION=3.4 VARIANT=alpine
    - VERSION=4.0 VARIANT=alpine
    - VERSION=4.1 VARIANT=alpine
    - VERSION=4.2 VARIANT=alpine
