dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - container_name="taiga_front"

script:
  - docker-compose build
  - travis_retry docker-compose up -d && docker-compose ps | grep "$container_name"
  - docker-compose ps
  - docker-compose logs

after_script:
  - docker images
  - docker ps -a

notifications:
  email: false

env: # Environments
    - VERSION=3.3 VARIANT=alpine
    - VERSION=3.4 VARIANT=alpine
    - VERSION=4.0 VARIANT=alpine
    - VERSION=4.1 VARIANT=alpine
    - VERSION=4.2 VARIANT=alpine
